labels:
  environment: "dev"

replicaCount: 2

podAnnotations:
  instrumentation.opentelemetry.io/inject-sdk: "default-instrumentation"
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

nodeSelector:
  karpenter.sh/capacity-type: "spot"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 1

ingress:
  enabled: false

configMap:
  data:
    RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: "redis"
    RETAIL_CHECKOUT_ENDPOINTS_ORDERS: "http://orders:80"
    RETAIL_CHECKOUT_SHIPPING_NAME_PREFIX: ""

secretProviderClass:
  parameters:
    region: us-east-1
    usePodIdentity: "true"
    objects: |
      - objectName: "/retail/dev/checkout/redis_host"
        objectType: "ssmparameter"
        objectAlias: REDIS_HOST
      - objectName: "/retail/dev/checkout/redis_port"
        objectType: "ssmparameter"
        objectAlias: REDIS_PORT
  secretObjects:
    - secretName: checkout-redis
      type: Opaque
      data:
        - objectName: REDIS_HOST
          key: REDIS_HOST
        - objectName: REDIS_PORT
          key: REDIS_PORT
