#values-dev.yaml

labels:
  environment: "dev"
  
#1. Start small in Dev
replicaCount: 2

#2. Dev-specific sizing
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    memory: 1Gi

#3. Use spot nodes
nodeSelector:
  karpenter.sh/capacity-type: "spot"

#4. Enable autoscaling to practice handling traffic spikes
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70


#5 Enable PDB so Karpener Spot interrupcions are handled
pdb:
  enabled: true
  minAvailable: 1

#5. Enable Ingress for Dev
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: retail-store-ui-dev
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:418674668464:certificate/332e3b54-06ad-45c3-b3b7-f1a728c86f29
    external-dns.alpha.kubernetes.io/hostname: retail-dev.matespinetti.me
  hosts:
    - host: "retail-dev.matespinetti.me"
      paths:
        - path: /
          pathType: Prefix
