apiVersion: v1
kind: Pod
metadata:
  name: catalog-pod
  labels:
    app: catalog
spec:
  containers:
    - name: catalog
      image: "public.ecr.aws/aws-containers/retail-store-sample-catalog:1.3.0"
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      resources:
        limits: # Maximum resources allowed
          cpu: "200m"
          memory: "256Mi"
        requests:  # Minimum resources required
          cpu: "100m"
          memory: "128Mi" 
      readinessProbe:
        httpGet:
          path: /health
          port: 8080