labels:
  environment: "dev"

replicaCount: 2

podAnnotations:
  instrumentation.opentelemetry.io/inject-sdk: "default-instrumentation"
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/actuator/prometheus"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

nodeSelector:
  karpenter.sh/capacity-type: "spot"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 1

ingress:
  enabled: false

externalServices:
  enabled: true
  services:
    - name: orders-db
      externalName: retail-dev-orders-db.cy960e2gkuba.us-east-1.rds.amazonaws.com
      ports:
        - name: postgres
          port: 5432
          protocol: TCP

configMap:
  data:
    RETAIL_ORDERS_PERSISTENCE_PROVIDER: "postgres"
    RETAIL_ORDERS_MESSAGING_PROVIDER: "sqs"

secretProviderClass:
  parameters:
    region: us-east-1
    usePodIdentity: "true"
    objects: |
      - objectName: "/retail/dev/orders/secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: DB_USER
            objectAlias: DB_USER
          - path: DB_PASS
            objectAlias: DB_PASS
          - path: DB_HOST
            objectAlias: DB_HOST
          - path: DB_NAME
            objectAlias: DB_NAME
          - path: SQS_QUEUE_URL
            objectAlias: SQS_QUEUE_URL
  secretObjects:
    - secretName: orders-secrets
      type: Opaque
      data:
        - objectName: DB_USER
          key: DB_USER
        - objectName: DB_PASS
          key: DB_PASS
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: SQS_QUEUE_URL
          key: SQS_QUEUE_URL
