labels:
  environment: "dev"

replicaCount: 2

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    memory: 1Gi

nodeSelector:
  karpenter.sh/capacity-type: "spot"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 1

ingress:
  enabled: false

secretProviderClass:
  parameters:
    region: us-east-1
    usePodIdentity: "true"
    objects: |
      - objectName: "/retail/dev/cart/items_table_name"
        objectType: "ssmparameter"
        objectAlias: ITEMS_TABLE_NAME
  secretObjects:
    - secretName: cart-items
      type: Opaque
      data:
        - objectName: ITEMS_TABLE_NAME
          key: ITEMS_TABLE_NAME
